version: '3.1'

services:
  pg:
    image: postgres
    container_name: pg
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-storage:/var/lib/postgresql/data
    ports:
      - 5432:5432

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   ports:
  #     - '5555:80'
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: intelcia@group.com
  #     PGADMIN_DEFAULT_PASSWORD: root
